#!/bin/bash
# $1 = $PROJECT_SOURCE_DIR
# $2 = $PROJECT_BINARY_DIR
# $3 = $CMAKE_CURRENT_SOURCE_DIR/${test}
# $4 = Mathematica kernel executable
"$1/nrginit/nrginit" "$4"
"$2/c++/nrg" 2>&1 | tee log
if [ $? -ne 0 ]; then
  echo "Abnormal termination. Skipping comparisons."
  exit 1
fi
"$1/test/compare.pl" "$3/ref"
