#!/bin/bash
set -o pipefail
# $1 = $PROJECT_SOURCE_DIR
# $2 = $CMAKE_CURRENT_SOURCE_DIR/${test}
# remaining arguments = MPI launcher, MPI flags, and nrg executable
project_source_dir="$1"
test_source_dir="$2"
shift 2
"$@" 2>&1 | tee log
if [ "${PIPESTATUS[0]}" -ne 0 ]; then
  echo "Abnormal termination. Skipping comparisons."
  exit 1
fi
if [ ! -f "DONE" ]; then
  echo "File DONE not found. Skipping comparisons."
  exit 1
fi
"${project_source_dir}/test/compare.pl" "${test_source_dir}/ref"
