#!/bin/sh
set -eu

"$1/kk" -v imaw.dat reaw.dat 2>verbose.txt
grep -q '^kk: configuration$' verbose.txt
grep -q '^  interpolation=akima$' verbose.txt
grep -q '^  input.lower_bound=auto ->' verbose.txt
grep -q '^  output.precision=16$' verbose.txt
"$2/test/compare.pl" "$3/ref"
