#!/bin/sh
set -eu
perl -e 'print pack("d*", 0.0625, 1.0, 0.1875, 2.0)' > spec.bin
cat <<'EOF' > mesh.dat
0 0
0.125 0
0.25 0
1 0
EOF
"$1/broaden" -c -L mesh.dat -o spec.bin 1 0.3 1e-4 >stdout.txt
cat <<'EOF' >expected
0 0
0.125 1
0.25 3
1 3
EOF
diff -u expected cumulative.dat
