#!/bin/sh
set -eu
if "$1/integ" imaw.dat >stdout.txt 2>stderr.txt; then
  echo "integ unexpectedly accepted invalid spline input" >&2
  exit 1
fi
test ! -s stdout.txt
printf '%s\n' 'integ: error: Interpolation energies must be strictly increasing.' >expected-stderr.txt
cmp expected-stderr.txt stderr.txt
