#!/bin/sh
# mixchain against adapt --integral + nrgchain on the tabulated density of nrgchain1. See param for why the tolerance
# is that of the FSOL tabulation rather than rounding.
set -eu
export PATH="$1:$PATH"

cp "$3/../../nrgchain/nrgchain1/Delta.dat" Delta.dat
cp Delta.dat Gamma_11-re.dat

adapt --integral P
adapt --integral N
nrgchain param

{ cat param; printf '\ndiscretization_files=true\n'; } >param-mixchain
mixchain -v param-mixchain >mixchain.log 2>&1

sh "$3/../compare_nrgchain.sh" 1e-6
