#!/bin/sh
set -eu

source_dir=$1
kernel=$2

"$kernel" -batchinput -batchoutput <<EOF
sourceDir = "$source_dir";
If[Check[Get["$source_dir/test/nrginit/rkpw.m"], \$Failed] === True, Exit[0], Exit[1]];
Exit[1];
EOF
