#!/bin/sh
set -eu
"$1/mats" -v -o spec.bin 1 0.11 10 2>verbose.txt
grep -q '^mats: configuration$' verbose.txt
grep -q '^  temperature=0.11$' verbose.txt
grep -q '^  matsubara_points=10$' verbose.txt
grep -q '^  matsubara_first_frequency=auto ->' verbose.txt
grep -q '^  matsubara_last_frequency=auto ->' verbose.txt
grep -q '^  output_precision=18$' verbose.txt
"$1/mats" -o -b -O bosonic.dat spec.bin 1 0.11 10
"$2/test/compare.pl" "$3/ref"
