#!/bin/sh
# Additional simplifications
math <<EOL

fn = "qst-triplets.dat";
<<"process3.m";

fn = "qst-tripletp.dat";
<<"process3.m";

fn = "qst-tripletm.dat";
<<"process3.m";

fn = "qst-orb-triplets.dat";
<<"process3.m";

fn = "qst-orb-tripletp.dat";
<<"process3.m";

fn = "qst-orb-tripletm.dat";
<<"process3.m";

Print["DONE"];

EOL
