#!/usr/bin/env perl
# Fix line breaks

$fn = "qst-triplets.dat";
$fnmma = "$fn.mma";
proc();

$fn = "qst-tripletp.dat";
$fnmma = "$fn.mma";
proc();

$fn = "qst-tripletm.dat";
$fnmma = "$fn.mma";
proc();

$fn = "qst-orb-triplets.dat";
$fnmma = "$fn.mma";
proc();

$fn = "qst-orb-tripletp.dat";
$fnmma = "$fn.mma";
proc();

$fn = "qst-orb-tripletm.dat";
$fnmma = "$fn.mma";
proc();


sub proc
{
    $fntmp = "$fn.tmp";

    print "$fnmma -> $fntmp\n";

    open(O, "<$fnmma") or die;
    open(T, ">$fntmp") or die;
    
    $first = 1;
    while (<O>) {
	chomp;
	if (/^\{\d/) {
	    print T "\n" if !$first;
	    print T "$_";
	    $first = 0;
	} else {
	    s/^\s*//;
	    print T " $_";
	}
    }
    print T "\n";
}
