#ifdef NRG_SYM_ALL
  #include "sym-DBLSU2.cc"
  #include "sym-DBLISOSZ.cc"
  #include "sym-ISOLR.cc"
  #include "sym-ISOSZLR.cc"
  #include "sym-NONE.cc"
  #include "sym-P.cc"
  #include "sym-PP.cc"
  #include "sym-SL.cc"
  #include "sym-SL3.cc"
  #include "sym-SPSU2LR.cc"
  #include "sym-SPSU2T.cc"
  #include "sym-SPU1LR.cc"
  #include "sym-SU2.cc"
  #include "sym-QSLR.cc"
  #include "sym-QST.cc"
  #include "sym-QSTZ.cc"
  #include "sym-QSZTZ.cc"
  #include "sym-QSZLR.cc"
  #include "sym-QJ.cc"
  #include "sym-U1.cc"
  #include "sym-SPSU2C3.cc"
  #include "sym-QSC3.cc"
#endif
  
