#!/usr/bin/env perl
use warnings;
use File::Basename;
my $dirname = dirname(__FILE__);

chomp(my $here = `pwd`);
my $ref = "$dirname/ref";
-d $ref or die;
chdir $ref;
foreach (<*>) {
  $fn = $_;
  -f $fn or next;
  -f "$here/$fn" or die "Result $fn does not exist.";
  print "$fn\n";
  system("diff $fn $here/$fn") == 0 or die "diff failed: $?";
}
print "OK!\n";
