#!/bin/sh
set -eu
"$1/specmoments" -o spec.bin 1 >results.dat
"$1/specmoments" -v -o spec.bin 1 >results-v.dat 2>verbose.txt
cmp results.dat results-v.dat
grep -q '^specmoments: configuration$' verbose.txt
grep -q '^  moment_mode=raw$' verbose.txt
grep -q '^  output_values=5$' verbose.txt
grep -q '^  output_precision=16$' verbose.txt
"$2/test/compare.pl" "$3/ref"
