#!/usr/bin/env perl
# Spectral function averaging : 4-column version
# Rok Zitko, rok.zitko@ijs.si, July 2019

use strict;
use warnings;
use FindBin qw($Bin);
use lib $Bin;
use TableIO qw(data_rows read_records scaled_mean);

@ARGV or die "Syntax: averagefiles4 <filename> ...\n";

my $columns = 4;
my @records = map { read_records($_, columns => $columns) } @ARGV;
my @tables = map { data_rows($_) } @records;
@{$tables[0]} or die "$ARGV[0]: expected at least one data row\n";

my $row_count = @{$tables[0]};
for my $file (1 .. $#tables) {
    my $found = @{$tables[$file]};
    $found == $row_count
        or die "$ARGV[$file]: expected $row_count data rows to match $ARGV[0], found $found\n";
    for my $row (0 .. $row_count - 1) {
        my ($reference, $current) = ($tables[0]->[$row], $tables[$file]->[$row]);
        my ($x, $other_x) = ($reference->{values}[0], $current->{values}[0]);
        $x == $other_x or die "$current->{path}:$current->{line}: column 1 ($other_x) "
            . "does not match $reference->{path}:$reference->{line} ($x)\n";
    }
}
my @means = map {
    my $row = $_;
    [map {
        my $column = $_;
        scaled_mean([map { $_->[$row]{values}[$column] } @tables],
                    "averagefiles4: row " . ($row + 1) . ", column " . ($column + 1));
    } 1 .. $columns - 1];
} 0 .. $row_count - 1;

my @results;
for my $row (0 .. $row_count - 1) {
    push @results, [$tables[0]->[$row]{tokens}[0], @{$means[$row]}];
}

my ($output, $row) = ('', 0);
for my $record (@{$records[0]}) {
    $output .= $record->{type} eq 'data'
        ? join(' ', @{$results[$row++]}) . "\n"
        : $record->{raw};
}
print $output;
