#!/usr/bin/env perl
# In a file containing data in blocks separated by empty lines,
# extract block N of non-empty lines.
# gzipped files are automatically decompressed on the fly.
# Rok Zitko, rok.zitko@ijs.si, 2009-2020

use strict;
use warnings;

if (@ARGV != 2) {
  die "Usage: block <filename> <N>.\n";
}

my $filename = shift;
my $N = shift;

my $arg;
if ($filename =~ /\.gz$/) {
    $arg = "gunzip -c $filename |";
} else {
    $arg = "<$filename";
}

open(F, $arg) or die "Can't open $filename: $!\n";

my @lastblock = ();
my @block = ();

my $ctr = 0;
while(<F>) {
    if (!/^#/) {
        if ($_ eq "\n") {
            $ctr++;
            @lastblock = @block;
            @block = ();
            if ($ctr == $N) {
                print @lastblock;
                exit(0);
            }
        } else {
            push(@block, $_);
        }
    }
}
