#!/usr/bin/perl
# Extract a column.
# Rok Zitko, rok.zitko@ijs.si, Apr, Nov 2008
# $Id$

use strict;
use warnings;
use FindBin qw($Bin);

if (@ARGV != 2) {
  die "Synthax: column <filename> <column>\n";
}

exec {$^X} $^X, "$Bin/columns", @ARGV;
die "Can't execute $Bin/columns: $!\n";
