#!/usr/bin/perl
# Dump file, skipping those lines where the first column has a value 
# smaller (in absolute value) than some given cut-off value.
# Rok Zitko, rok.zitko@ijs.si, Oct 2010

use warnings;
use strict;

if (@ARGV < 1) {
    die "Usage: cutoutlow <cutoff> [filename]\n";
}     

my $cutoff = eval(shift);

while (<>) {
  if (!/^#/) {
    chomp;
    my @d = split;
    my $x = $d[0];
    
    if (abs($x) >= $cutoff) {
	print "@d\n";
    }
  } else {
    print;
  }
}
