#!/usr/bin/perl
# Extract a column with a given header keyword. The header line is the last lin$
# with a # character which contains the names of the columns.
# Rok Zitko, rok.zitko@ijs.si, Mar 2008
# $Id$

use strict;
use warnings;
use FindBin qw($Bin);

if (@ARGV != 2) {
  die "Synthax: extractcolumn <filename> <keyword>\n";
}

exec {$^X} $^X, "$Bin/extractcolumns", @ARGV;
die "Can't execute $Bin/extractcolumns: $!\n";
