#!/usr/bin/env perl
# Gather the last custom row from completed numeric run directories.

use strict;
use warnings;
use FindBin qw($Bin);
use lib $Bin;
use TableIO qw(atomic_write data_rows parse_number read_records);

@ARGV <= 1 or die "Usage: gather [parameter]\n";
my $parameter_name = shift // 'UNDEF';
opendir(my $dh, '.') or die "Can't open current directory: $!\n";
my @dirs = map { "./$_" }
           sort { $a <=> $b || $a cmp $b }
           grep { /\A\d+\z/ && -d $_ } readdir($dh);
closedir($dh) or die "Can't finish reading current directory: $!\n";

my (@headers, @output_rows);
my @status = ("dirs = [@dirs]\n");
my ($sources, $columns) = (0, undef);
for my $dir (@dirs) {
    if (!-e "$dir/DONE") {
        push @status, "$dir - not yet" . (-e "$dir/RUNNING" ? " - running" : '') . "\n";
        next;
    }

    my $path = "$dir/custom";
    my $records = read_records($path);
    my $data = data_rows($records);
    @$data or die "$path: no data rows\n";
    my @source_headers;
    for my $record (@$records) {
        last if $record->{type} eq 'data';
        next unless $record->{type} eq 'comment';
        (my $line = $record->{raw}) =~ s/[\r\n]+\z//;
        push @source_headers, $line;
    }
    if (!$sources) {
        @headers = @source_headers;
    } elsif (@source_headers != @headers
             || grep { $source_headers[$_] ne $headers[$_] } 0 .. $#headers) {
        die "$path: headers do not match the first completed run\n";
    }
    for my $record (@$data) {
        my $width = @{$record->{tokens}};
        defined($columns) && $width != $columns
            and die "$path:$record->{line}: expected $columns columns, found $width\n";
        $columns //= $width;
    }

    open(my $param_fh, '-|', "$Bin/getparam", $parameter_name, "$dir/param")
        or die "Can't run $Bin/getparam for $dir: $!\n";
    my @parameter = <$param_fh>;
    close($param_fh) or die "getparam failed for $dir (status $?)\n";
    @parameter == 1 or die "$dir/param: getparam returned " . scalar(@parameter) . " lines\n";
    $parameter[0] =~ s/[\r\n]+\z//;
    $parameter[0] =~ s/\A\s+|\s+\z//g;
    parse_number($parameter[0], "$dir/param: parameter $parameter_name");

    my @fields = @{$data->[-1]{tokens}};
    $fields[0] = $parameter[0];
    push @output_rows, "     @fields\n";
    push @status, "$dir - done\n";
    $sources++;
}

$sources or die "No completed numeric run directories found\n";
if (@headers) {
    my @names = split ' ', $headers[-1];
    shift(@names) eq '#' && @names == $columns
        or die "custom header does not describe $columns columns\n";
    $names[0] = $parameter_name;
    $headers[-1] = '# ' . join(' ', @names);
}
my $content = join('', map { "$_\n" } @headers) . join('', @output_rows);
atomic_write('custom.dat', $content);
print @status;
