#!/usr/bin/env perl
# Extract Nz
# Rok Zitko, rok.zitko@ijs.si, Dec 2018

use strict;
use warnings;

@ARGV <= 1 or die "Usage: getNz [param filename]\n";
my $file = shift // 'param.loop';

open(my $fh, '<', $file) or die "Can't open $file for reading: $!\n";
my @values;
while (my $line = <$fh>) {
    if ($line =~ /^\s*\$Nz\s*=\s*([^;#]+?)\s*;?\s*(?:#.*)?$/) {
        push @values, $1;
    }
}
close($fh) or die "Can't finish reading $file: $!\n";

@values == 1
    or die @values ? "getNz: Ambiguous \$Nz in $file\n"
                   : "getNz: \$Nz not found in $file\n";
print STDOUT "$values[0]\n" or die "Can't write \$Nz: $!\n";
