#!/usr/bin/perl
# Extract a parameter from 'param' file
# Rok Zitko, rok.zitko@ijs.si, 2008-2026

use strict;
use warnings;

@ARGV == 1 || @ARGV == 2
    or die "Usage: getparam <keyword> [param filename]\n";
my ($keyword, $file) = @ARGV;
$file //= 'param';

open(my $fh, '<', $file) or die "Can't open $file for reading: $!\n";
my @values;
while (1) {
    $! = 0;
    my $line = <$fh>;
    if (!defined($line)) {
        $! and die "Can't read $file: $!\n";
        last;
    }
    push @values, $1 if $line =~ /^\s*\Q$keyword\E\s*=\s*(.*)/;
}
close($fh) or die "Can't finish reading $file: $!\n";

@values == 1
    or die @values ? "getparam: Keyword $keyword is ambiguous in $file\n"
                   : "getparam: Keyword $keyword not found in $file\n";
print STDOUT "$values[0]\n" or die "Can't write parameter: $!\n";
close(STDOUT) or die "Can't finish writing parameter: $!\n";
