#!/bin/sh

integ=integ
case $0 in
  */*) candidate=${0%/*}/integ; test ! -x "$candidate" || integ=$candidate ;;
esac

case $# in
  1) exec "$integ" --interpolation linear --lower-bound=-1 --upper-bound=1 -- "$1" ;;
  3) exec "$integ" --interpolation linear --lower-bound="$2" --upper-bound="$3" -- "$1" ;;
  *) printf '%s\n' 'Syntax: integrateab filename [a b]' >&2; exit 1 ;;
esac
