#!/usr/bin/perl
# Join columns into a table
# Rok Zitko, rok.zitko@ijs.si, Mar 2008
# $Id$

use warnings;
use strict;
use FindBin qw($Bin);
use lib $Bin;
use TableIO qw(data_rows read_records);

if (@ARGV != 2) {
    die "Syntax: joincolumns <filename1> <filename2>\n";
}

my ($filename1, $filename2) = @ARGV;
my $records1 = read_records($filename1, minimum_columns => 1, fixed_columns => 1);
my $records2 = read_records($filename2, minimum_columns => 1, fixed_columns => 1);
my $rows1 = data_rows($records1);
my $rows2 = data_rows($records2);

my ($count1, $count2) = (scalar @$rows1, scalar @$rows2);
$count1 == $count2
    or die "$filename1 and $filename2: data row count mismatch ($count1 != $count2)\n";

my @results;
for my $row (0 .. $count1 - 1) {
    push @results, [@{$rows1->[$row]{tokens}}, @{$rows2->[$row]{tokens}}];
}

my ($output, $row) = ('', 0);
for my $record (@$records1) {
    $output .= $record->{type} eq 'data'
        ? join(' ', @{$results[$row++]}) . "\n"
        : $record->{raw};
}
print $output;
