#!/usr/bin/perl
# Mxing the y-columns of two files. Checks if the x-columns match.
# Rok Zitko, rok.zitko@ijs.si, 2024

use strict;
use warnings;
use FindBin qw($Bin);
use lib $Bin;
use TableIO qw(data_rows finite_result parse_number read_records);

@ARGV == 4 or die "Syntax: mixy <factor1> <filename1> <factor2> <filename2>\n";

my ($factor1_text, $filename1, $factor2_text, $filename2) = @ARGV;
my $factor1 = parse_number($factor1_text, 'mixy: factor 1');
my $factor2 = parse_number($factor2_text, 'mixy: factor 2');
my $records1 = read_records($filename1, minimum_columns => 2, fixed_columns => 1);
my $records2 = read_records($filename2, minimum_columns => 2, fixed_columns => 1);
my $rows1 = data_rows($records1);
my $rows2 = data_rows($records2);

my ($count1, $count2) = (scalar @$rows1, scalar @$rows2);
$count1 == $count2
    or die "$filename1 and $filename2: data row count mismatch ($count1 != $count2)\n";

my @results;
for my $row (0 .. $count1 - 1) {
    my ($left, $right) = ($rows1->[$row], $rows2->[$row]);
    my ($width1, $width2) = (scalar @{$left->{tokens}}, scalar @{$right->{tokens}});
    my ($where1, $where2) = ("$left->{path}:$left->{line}", "$right->{path}:$right->{line}");
    $width1 == $width2
        or die "$where1 and $where2: column count mismatch ($width1 != $width2)\n";
    $left->{values}[0] == $right->{values}[0]
        or die "$where1 and $where2: column 1 mismatch ($left->{values}[0] != $right->{values}[0])\n";

    my @output = @{$left->{tokens}};
    $output[1] = finite_result(
        $factor1 * $left->{values}[1] + $factor2 * $right->{values}[1],
        "$where1: column 2");
    push @results, \@output;
}

my ($output, $row) = ('', 0);
for my $record (@$records1) {
    $output .= $record->{type} eq 'data'
        ? join(' ', @{$results[$row++]}) . "\n"
        : $record->{raw};
}
print $output;
