#!/usr/bin/perl
# Integrate column data by trapezoid rule - SECOND MOMENT CALCULATION
# Rok Zitko, zitko@theorie.physik.uni-goettingen.de, Feb, Jun 2008

use warnings;

$xprev = 0;
$yprev = 0;
$sum = 0;

while (<>) {
  chomp;
  @d = split;
  $x = $d[0];
  $y = $d[1];
  
  if ($. != 1) {
    my $f = ($y + $yprev)/2.0;
    my $xavg = ($x + $xprev)/2.0;
    my $integrand = $f * $xavg**2; # Second moment
    my $width = $x - $xprev;
    $sum += $width * $integrand;
  }
  
  $xprev = $x;
  $yprev = $y;
}

print "$sum\n";
