#!/usr/bin/perl
# Keep only those lines where the first value is negative
# Rok Zitko, rok.zitko@ijs.si, Feb 2015

use warnings;
use strict;
use FindBin qw($Bin);
use lib $Bin;
use TableIO qw(join_outputs read_records);

my @paths = @ARGV ? @ARGV : ('-');
my $stdin_count = grep { $_ eq '-' } @paths;
$stdin_count <= 1 or die "negativepart: standard input may be specified at most once\n";
my @sources = map {
    read_records($_, minimum_columns => 1, fixed_columns => 1, numeric_columns => 1)
} @paths;

my @parts;
for my $records (@sources) {
    my $part = '';
    for my $record (@$records) {
        $part .= $record->{raw}
            if $record->{type} ne 'data' || $record->{values}[0] < 0;
    }
    push @parts, $part;
}
print STDOUT join_outputs(@parts) or die "Can't write negativepart output: $!\n";
close(STDOUT) or die "Can't finish negativepart output: $!\n";
