#!/usr/bin/env perl

use strict;
use warnings;
use FindBin qw($Bin);
use lib $Bin;
use TableIO ();

our $REPORT_COORDINATES = 2;
my $loaded = do "$Bin/report";
die $@ if $@;
defined($loaded) or die "Can't load $Bin/report: $!\n";
$loaded or die "$Bin/report did not complete\n";
