#!/usr/bin/perl
# Scale the first two columns in tabulated data by factors given on
# the command line 
# Rok Zitko, rok.zitko@ijs.si, Sep 2009

use warnings;
use strict;
use FindBin qw($Bin);
use lib $Bin;
use TableIO qw(finite_result join_outputs parse_number read_records);

@ARGV >= 2 or die "Usage: scalexy <factor x> <factor y> [filename ...]\n";
my $factorx = parse_number(shift @ARGV, 'scalexy: x factor');
my $factory = parse_number(shift @ARGV, 'scalexy: y factor');
my @paths = @ARGV ? @ARGV : ('-');
my $stdin_count = grep { $_ eq '-' } @paths;
$stdin_count <= 1 or die "scalexy: standard input may be specified at most once\n";

my @sources = map {
    read_records($_, minimum_columns => 2, fixed_columns => 1, numeric_columns => 2)
} @paths;
my @parts;
for my $records (@sources) {
    my $part = '';
    for my $record (@$records) {
        if ($record->{type} eq 'data') {
            my @tokens = @{$record->{tokens}};
            $tokens[0] = finite_result($record->{values}[0] * $factorx,
                                       "$record->{path}:$record->{line}: column 1");
            $tokens[1] = finite_result($record->{values}[1] * $factory,
                                       "$record->{path}:$record->{line}: column 2");
            $part .= join(' ', @tokens) . "\n";
        } else {
            $part .= $record->{raw};
        }
    }
    push @parts, $part;
}
print STDOUT join_outputs(@parts) or die "Can't write scalexy output: $!\n";
close(STDOUT) or die "Can't finish scalexy output: $!\n";
