#!/usr/bin/perl
# Shift the first column in tabulated data by a value given on command line
# Rok Zitko, zitko@theorie.physik.uni-goettingen.de, Feb 2008, Aug 2009

use strict;
use warnings;
use FindBin qw($Bin);
use lib $Bin;
use TableIO qw(finite_result join_outputs parse_number read_records);

@ARGV >= 1 or die "Usage: shiftx <shift> [filename ...]\n";
my $shift = parse_number(shift @ARGV, 'shiftx: shift');
my @paths = @ARGV ? @ARGV : ('-');
my $stdin_count = grep { $_ eq '-' } @paths;
$stdin_count <= 1 or die "shiftx: standard input may be specified at most once\n";

my @sources = map {
    read_records($_, minimum_columns => 1, fixed_columns => 1, numeric_columns => 1)
} @paths;
my @parts;
for my $records (@sources) {
    my $part = '';
    for my $record (@$records) {
        if ($record->{type} eq 'data') {
            my @tokens = @{$record->{tokens}};
            $tokens[0] = finite_result($record->{values}[0] + $shift,
                                       "$record->{path}:$record->{line}: column 1");
            $part .= join(' ', @tokens) . "\n";
        } else {
            $part .= $record->{raw};
        }
    }
    push @parts, $part;
}
print STDOUT join_outputs(@parts) or die "Can't write shiftx output: $!\n";
close(STDOUT) or die "Can't finish shiftx output: $!\n";
