#!/usr/bin/perl
# Shift the second column in tabulated data by a value given on command line
# Rok Zitko, zitko@theorie.physik.uni-goettingen.de, Feb 2008, Aug 2009

use strict;
use warnings;
use FindBin qw($Bin);
use lib $Bin;
use TableIO qw(finite_result join_outputs parse_number read_records);

@ARGV >= 1 or die "Usage: shifty <shift> [filename ...]\n";
my $shift = parse_number(shift @ARGV, 'shifty: shift');
my @paths = @ARGV ? @ARGV : ('-');
my $stdin_count = grep { $_ eq '-' } @paths;
$stdin_count <= 1 or die "shifty: standard input may be specified at most once\n";

my @sources = map {
    read_records($_, minimum_columns => 2, fixed_columns => 1, numeric_columns => 2)
} @paths;
my @parts;
for my $records (@sources) {
    my $part = '';
    for my $record (@$records) {
        if ($record->{type} eq 'data') {
            my @tokens = @{$record->{tokens}};
            $tokens[1] = finite_result($record->{values}[1] + $shift,
                                       "$record->{path}:$record->{line}: column 2");
            $part .= join(' ', @tokens) . "\n";
        } else {
            $part .= $record->{raw};
        }
    }
    push @parts, $part;
}
print STDOUT join_outputs(@parts) or die "Can't write shifty output: $!\n";
close(STDOUT) or die "Can't finish shifty output: $!\n";
