#!/usr/bin/perl
# Subtract one table from another [element by element]
# Rok Zitko, rok.zitko@ijs.si, Mar, Oct 2008
# $Id$

use strict;
use warnings;
use FindBin qw($Bin);
use lib $Bin;
use TableIO qw(data_rows finite_result read_records);

if (@ARGV != 2) {
    die "Synthax: subtract <filename1> <filename2>\n";
}

my ($filename1, $filename2) = @ARGV;
my $records1 = read_records($filename1, minimum_columns => 1, fixed_columns => 1);
my $records2 = read_records($filename2, minimum_columns => 1, fixed_columns => 1);
my $rows1 = data_rows($records1);
my $rows2 = data_rows($records2);

my ($count1, $count2) = (scalar @$rows1, scalar @$rows2);
$count1 == $count2
    or die "$filename1 and $filename2: data row count mismatch ($count1 != $count2)\n";

my @results;
for my $row (0 .. $count1 - 1) {
    my ($left, $right) = ($rows1->[$row], $rows2->[$row]);
    my ($width1, $width2) = (scalar @{$left->{tokens}}, scalar @{$right->{tokens}});
    my ($where1, $where2) = ("$left->{path}:$left->{line}", "$right->{path}:$right->{line}");
    $width1 == $width2
        or die "$where1 and $where2: column count mismatch ($width1 != $width2)\n";

    my @output;
    for my $column (0 .. $width1 - 1) {
        push @output, finite_result($left->{values}[$column] - $right->{values}[$column],
                                    "$where1: column " . ($column + 1));
    }
    push @results, \@output;
}

my ($output, $row) = ('', 0);
for my $record (@$records1) {
    $output .= $record->{type} eq 'data'
        ? join(' ', @{$results[$row++]}) . "\n"
        : $record->{raw};
}
print $output;
