#!/bin/sh
set -eu
"$1/unitary" -vv -o res.dat mat.dat mat.dat mat.dat 2>verbose.txt
grep -q '^unitary: configuration$' verbose.txt
grep -q '^  input_a_rows=auto ->' verbose.txt
grep -q '^  input_b_rows=auto ->' verbose.txt
grep -q '^  input_c_rows=auto ->' verbose.txt
grep -q '^  output_precision=18$' verbose.txt
"$2/test/compare.pl" "$3/ref"
