#!/bin/sh
set -e

export PATH="$1:$PATH"

test ! -d template
instantiate > instantiate.out

test -s data

count=$(grep -c '^f ' data)
test "$count" = 2

for file in xi.dat zeta.dat theta.dat xi1.dat zeta1.dat theta1.dat val vec mat mat.res ham param.param param.dmft param.extra solverlog solverlogneg; do
  test ! -e "$file"
done

for file in vec.* ham.*; do
  test ! -e "$file"
done
