#!/bin/sh
set -eu

export PATH="$1:$PATH"

test ! -d template
instantiate -v >instantiate.out 2>verbose.txt

grep -q '^instantiate: configuration$' verbose.txt
grep -q '^  mode=auto -> full ' verbose.txt
grep -q '^  template.data=auto ->' verbose.txt
grep -q '^  template.scale_factor=auto ->' verbose.txt
grep -q '^  nrgchain.mMAX=' verbose.txt
grep -q '^  nrgchain.tridiagonalize=' verbose.txt

test -s data

count=$(grep -c '^f ' data)
test "$count" = 2

for file in xi.dat zeta.dat theta.dat xi1.dat zeta1.dat theta1.dat val vec mat mat.res ham param.param param.dmft param.extra solverlog solverlogneg; do
  test ! -e "$file"
done

for file in vec.* ham.*; do
  test ! -e "$file"
done
