#!/bin/sh
set -eu

export PATH="$1:$PATH"
case "$CHAIN_TEST_BACKEND" in legacy) method=lanczos ;; rkpw) method=rkpw ;; *) exit 1 ;; esac

test ! -d template
rm -f data
instantiate -v >instantiate.out 2>verbose.txt
grep -q "^  nrgchain.tridiag_method=$method$" verbose.txt

grep -q '^instantiate: configuration$' verbose.txt
grep -q '^  mode=auto -> full ' verbose.txt
grep -q '^  template.data=auto ->' verbose.txt
grep -q '^  template.scale_factor=auto ->' verbose.txt
grep -q '^  nrgchain.mMAX=' verbose.txt
grep -q '^  nrgchain.tridiagonalize=' verbose.txt

test -s data

count=$(grep -c '^f ' data)
test "$count" = 2

for file in xi.dat zeta.dat theta.dat xi1.dat zeta1.dat theta1.dat val vec mat mat.res ham param.param param.dmft param.extra solverlog solverlogneg; do
  test ! -e "$file"
done

for file in vec.* ham.*; do
  test ! -e "$file"
done
