#!/bin/sh
set -eu
mkdir -p 1 2
perl -e 'print pack("d*", 1.0, 2.0)' > 1/spec.bin
perl -e 'print pack("d*", 1.0, 4.0)' > 2/spec.bin
"$1/binavg" spec.bin 2 > stdout.txt
perl -e 'open my $fh, "<", "spec.bin" or die; read($fh, my $buf, 16) == 16 or die; my @d = unpack("d*", $buf); exit(($d[0] == 1.0 && abs($d[1] - 3.0) < 1e-12) ? 0 : 1);'
