#!/usr/bin/perl

my $j = 0.2;
my $j2 = $j ** 2;

my $pi = 4.0*atan2(1,1);
my $factor = ($pi ** 2)/2.0;

$dir = ".";

system("cp $dir/spec_DMNRG_dens_A_f-A_f-d.dat Ad.dat");
system("cp $dir/spec_DMNRG_dens_A_f-A_f-u.dat Au.dat");
system("sumy Ad.dat Au.dat >Asum.dat");
system("scaley 0.5 Asum.dat >Af.dat");

system("cp $dir/spec_DMNRG_dens_O_f-A_f-d.dat OAd.dat");
system("cp $dir/spec_DMNRG_dens_O_f-A_f-u.dat OAu.dat");
system("sumy OAd.dat OAu.dat >OAsum.dat");
system("scaley 0.5 OAsum.dat >OAf.dat");

system("scaley $j2 $dir/spec_DMNRG_dens_O_f-O_f-d.dat >Od.dat");
system("scaley $j2 $dir/spec_DMNRG_dens_O_f-O_f-u.dat >Ou.dat");

my $factorhalf = $factor/2;

system("sumy Od.dat Ou.dat >Osum.dat");
system("scaley $factorhalf Osum.dat >Osc.dat");

